### PR TITLE
Added Shuttle stops on campus dataset

### PR DESCRIPTION
**Pull request by Ankurmangal**
Added Shuttle stops on campus dataset

### CODE REVIEW

**Comment by jmtjendra** [comment]
Hi Ankur, looks good so far. Add a space before the opening brackets for the buildings and there's a typo on line 14: "lpt".

**Comment by Ankurmangal** [comment]
Changes made according to the comment.

**Comment by jmtjendra** [comment]
Found a few more things:
-	Line 2: Typo “Mathews” --> “Matthews”
-	Line 3: Typo “Reseach” --> “Research”
-	Line 7: Typo “G.Needled” --> “G. Needles”
-	Line 14: Typo “St.Paul’s” --> “St. Paul’s”

**Comment by Ankurmangal** [comment]
Fixed the typo's .

**Pull request merged**
