### PR TITLE
Update visitor_parking.csv

### PR DESCRIPTION
**Pull request by dsmccrac**
Updated CGR Parking rates from $1hr/$4day max to $3hr/$9 day

### CODE REVIEW

**Comment by sbobkin** [comment]
Thanks for the update. Is there anywhere online this new rate is listed, I briefly looked online, but it mentions rates are at meter. I'm okay with that, if you can confirm that's where the change is coming from.

**Comment by jmtjendra** [comment]
Hi @sbobkin ,

Here's the original request:

From: Melinda Mah <melinda.mah@uwaterloo.ca>
Date: Friday, September 7, 2018 at 9:42 AM
To: Donald Duff-McCracken <dsmccrac@uwaterloo.ca>
Subject: Update to Campus Map Parking Information
 
Good morning,
 
I would like to update the information on the campus map regarding parking rates at Conrad Grebel University College. Our parking rates are $3 per hour, up to a maximum of $9 daily.
 
Cheers,
 
Melinda Mah
Office Assistant and Receptionist
 
140 Westmount Rd. N.
Waterloo, ON N2L 3G6
519-885-0220 x24200
Fax: 519-885-0014
melinda.mah@uwaterloo.ca
grebel.ca

**Comment by dsmccrac** [comment]
Hi Sergei

I was emailed from the Conrad Grebel office administrator. See message below. And it is listed on this page - https://uwaterloo.ca/grebel/contact-us

Thanks!
don


From: Melinda Mah <melinda.mah@uwaterloo.ca<mailto:melinda.mah@uwaterloo.ca>>
Date: Friday, September 7, 2018 at 9:42 AM
To: Donald Duff-McCracken <dsmccrac@uwaterloo.ca<mailto:dsmccrac@uwaterloo.ca>>
Subject: Update to Campus Map Parking Information

Good morning,

I would like to update the information on the campus map regarding parking rates at Conrad Grebel University College. Our parking rates are $3 per hour, up to a maximum of $9 daily.

Cheers,

Melinda Mah
Office Assistant and Receptionist

140 Westmount Rd. N.
Waterloo, ON N2L 3G6
519-885-0220 x24200
Fax: 519-885-0014
melinda.mah@uwaterloo.ca<mailto:melinda.mah@uwaterloo.ca>
grebel.ca<https://uwaterloo.ca/grebel/>

[grebel_signature_logo]<http://uwaterloo.ca/grebel>

This E-mail contains privileged and confidential information intended only for the individual or entity named in the message.  If the reader of this message is not the intended recipient, or the agent responsible to deliver it to the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is prohibited.  If this communication was received in error, please notify the sender by reply E-mail immediately, and delete and destroy the original message.






------------------------------------
Donald Duff-McCracken
Technical Services Manager
Mapping, Analysis & Design
Faculty of Environment
University of Waterloo
(519) 888-4567 x32151
https://uwaterloo.ca/environment-computing/about/people
------------------------------------
This email communication is intended as a private communication for the sole use of the primary addressee and those individuals listed for copies in the original message. The information contained in this email is private and confidential and If you are not an intended recipient you are hereby notified that copying, forwarding or other dissemination or distribution of this communication by any means is prohibited.  If you are not specifically authorized to receive this email and if you believe that you received it in error please notify the original sender immediately.

**Comment by sbobkin** [comment]
Thanks!

**Pull request merged**
