### PR TITLE
Add thank-you days

### PR DESCRIPTION
**Pull request by lkmorlan**
Add the thank-you days announced on Feb. 4.

### CODE REVIEW

**Comment by lkmorlan** [comment]
I still don't see these on:
https://openapi.data.uwaterloo.ca/v3/HolidayDates/paidholidays/ics
What has to be done to deploy these changes?

**Comment by sbobkin** [comment]
@lkmorlan apologies, should be there now? Can you confirm please.

**Comment by lkmorlan** [comment]
I still don't see them. I used wget to download the file and checked for the dates.

**Comment by sbobkin** [comment]
That endpoint has a very aggressive 90 day cache that doesn't always evict, I've forced it to clear and it looks like the content is in the ICS file now: 

```
BEGIN:VEVENT
UID:AdditionalDay2/22/2022
DESCRIPTION:Additional Day
SUMMARY:Additional Day
DTSTART;VALUE=DATE:20220222
END:VEVENT
BEGIN:VEVENT
UID:AdditionalDay10/11/2022
DESCRIPTION:Additional Day
SUMMARY:Additional Day
DTSTART;VALUE=DATE:20221011
END:VEVENT
```

**Comment by lkmorlan** [comment]
I am now seeing it in my calendar. Thanks.

**Pull request merged**
